trigger:
- main  # Adjust the branch as needed

pool:
  vmImage: 'ubuntu-latest'

steps:
# Step 1: Pull the OWASP ZAP Docker Image
- task: Bash@3
  displayName: 'Pull OWASP ZAP Docker Image'
  inputs:
    targetType: 'inline'
    script: |
      docker pull owasp/zap2docker-stable

# Step 2: Run OWASP ZAP Container
- task: Bash@3
  displayName: 'Run OWASP ZAP Scan'
  inputs:
    targetType: 'inline'
    script: |
      docker run -v $(System.DefaultWorkingDirectory):/zap/wrk/:rw owasp/zap2docker-stable zap-baseline.py \
        -t https://demo.testfire.net \
        -r zap_report.html \
        -J zap_report.json

# Step 3: Publish OWASP ZAP Report
- task: PublishPipelineArtifact@1
  displayName: 'Publish ZAP Report'
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/zap_report.html'
    artifactName: 'ZAP Report'
