name: ci

on:
  push:
    branches: main

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}		
          run : docker build . --file Docker/Dockerfile --tag my-image-name:$(date +%s) && docker tag my-image-name:$(date +%s) manojsinghceh/demo-az-pipeline 
